# Generated by Django 5.2.5 on 2025-08-23 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('incident_type', models.CharField(choices=[('fall', 'Fall'), ('medication', 'Medication Error'), ('behavioral', 'Behavioral'), ('equipment', 'Equipment Failure'), ('infection', 'Infection'), ('injury', 'Injury'), ('other', 'Other')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('location', models.CharField(max_length=255)),
                ('resident', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('reporter', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
