# Generated by Django 5.2.5 on 2025-08-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='incident_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_type',
            field=models.CharField(choices=[('Fall', 'Fall'), ('Medication', 'Medication Error'), ('Behavioral', 'Behavioral'), ('Equipment', 'Equipment Failure'), ('Infection', 'Infection'), ('Injury', 'Injury'), ('Other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='incident',
            name='severity',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], max_length=10),
        ),
    ]
