# Generated by Django 5.2.5 on 2025-08-25 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0002_incident_incident_date_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='actions_taken',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='reported_to_manager',
            field=models.BooleanField(default=False),
        ),
    ]
